
import static java.lang.Math.pow;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KEVIN FABRICIO
 */
public class PICM extends javax.swing.JFrame {

    /**
     * Creates new form PICM
     */
    public PICM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lambda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        k = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Wq = new javax.swing.JLabel();
        Wn = new javax.swing.JLabel();
        W = new javax.swing.JLabel();
        Ln = new javax.swing.JLabel();
        Lq = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        Pne = new javax.swing.JLabel();
        Pn = new javax.swing.JLabel();
        Pk = new javax.swing.JLabel();
        Po = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Ctte = new javax.swing.JLabel();
        Ctts = new javax.swing.JLabel();
        Cttse = new javax.swing.JLabel();
        Cts = new javax.swing.JLabel();
        Ct = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cte = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cts = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ctse = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cs = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        horas = new javax.swing.JTextField();
        Cb = new javax.swing.JComboBox<>();
        n1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Num = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PICM");

        jLabel2.setText("Lambda :");

        lambda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lambdaActionPerformed(evt);
            }
        });

        jLabel3.setText("Mu :");

        jLabel4.setText("K :");

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("N :");

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        jLabel6.setText("Po :");

        jLabel7.setText("Pk :");

        jLabel8.setText("Pn :");

        jLabel9.setText("Pne :");

        jLabel10.setText("L :");

        jLabel11.setText("Lq :");

        jLabel12.setText("Ln :");

        jLabel13.setText("W :");

        jLabel14.setText("Wn :");

        jLabel15.setText("Wq :");

        Wq.setText("jLabel16");

        Wn.setText("jLabel16");

        W.setText("jLabel16");

        Ln.setText("jLabel16");

        Lq.setText("jLabel16");

        L.setText("jLabel16");

        Pne.setText("jLabel16");

        Pn.setText("jLabel16");

        Pk.setText("jLabel16");

        Po.setText("jLabel16");

        jLabel16.setText("COSTOS");

        jLabel17.setText("CD Tiempo Espera en Cola CTTE");

        jLabel18.setText("CD Tiempo en el Sistema CTTS ");

        jLabel19.setText("CD Tiempo de Servicio CTTSE");

        jLabel20.setText("CD Servidor CTS");

        jLabel21.setText("CTD Sistema CT");

        Ctte.setText("jLabel22");

        Ctts.setText("jLabel22");

        Cttse.setText("jLabel22");

        Cts.setText("jLabel22");

        Ct.setText("jLabel22");

        jLabel22.setText("Costo Diario T Cola CTE :");

        jLabel23.setText("Costo Diario T Sistema CTS :");

        cts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctsActionPerformed(evt);
            }
        });

        jLabel24.setText("Costo Diario T Servicio CTSE :");

        jLabel25.setText("Costo Servidor CS :");

        jLabel26.setText("Horas :");

        Cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">=", "<=" }));
        Cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbActionPerformed(evt);
            }
        });

        jLabel27.setText("Respuesta :");

        Num.setText("jLabel28");

        jLabel28.setText("PROBABILIDAD");

        jButton2.setText("CAL COSTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 624, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lambda)
                            .addComponent(mu)
                            .addComponent(k)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L)
                            .addComponent(Pne)
                            .addComponent(Pn)
                            .addComponent(Po)
                            .addComponent(Pk))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Wq)
                            .addComponent(Wn)
                            .addComponent(W)
                            .addComponent(Ln)
                            .addComponent(Lq))
                        .addGap(59, 59, 59))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Ctte))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cttse))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Ctts)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Num)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel25))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cts, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ctse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(56, 56, 56)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cts)
                            .addComponent(Ct))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(Lq))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(Ln))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(W))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(Wn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(Wq)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Pn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pne)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(L))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Po))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Pk))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(Num)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(cte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(cts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(ctse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(Ctte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Ctts)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(Cts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(Ct))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Cttse))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lambdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lambdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lambdaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       double l=0;
       double m=0;
       double k=0;
       double h=0, cte=0, cts=0, ctse=0, cs=0;
       int n=0,n1=0, cb=0;
       
       
       l=Double.parseDouble(this.lambda.getText());
       m=Double.parseDouble(this.mu.getText());
       k=Double.parseDouble(this.k.getText());
       n=Integer.parseInt(this.n.getText());
       n1=Integer.parseInt(this.n1.getText());
       cb=this.Cb.getSelectedIndex();
       
       
       double cPo=CalcularPo(l,m,k);
       Po.setText(String.valueOf(cPo));
       
       double cPk=CalcularPk(l,m,k);
       Pk.setText(String.valueOf(cPk));
       
       double cPn=CalcularPn(l,m,k,n);
       Pn.setText(String.valueOf(cPn));
       
       double cPne=CalcularPne(l,m,k);
       Pne.setText(String.valueOf(cPne));
       
       double cL=CalcularL(l,m,k);
       L.setText(String.valueOf(cL));
       
       double cLq=CalcularLq(l,m,k);
       Lq.setText(String.valueOf(cLq));
       
       double cLn=CalcularLn(l,m,k);
       Ln.setText(String.valueOf(cLn));
       
       double cW=CalcularW(l,m,k);
       W.setText(String.valueOf(cW));
       
       double cWq=CalcularWq(l,m,k);
       Wq.setText(String.valueOf(cWq));
       
       double cWn=CalcularWn(l,m,k);
       Wn.setText(String.valueOf(cWn));
              
       double cP=Probabilidad(cb,l,m,k,n1);
       Num.setText(String.valueOf(cP));
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void CbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbActionPerformed

    private void ctsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       double l=0;
       double m=0;
       double k=0;
       double h=0, cte=0, cts=0, ctse=0, cs=0;
       
       l=Double.parseDouble(this.lambda.getText());
       m=Double.parseDouble(this.mu.getText());
       k=Double.parseDouble(this.k.getText());
       h=Double.parseDouble(this.horas.getText());
       cte=Double.parseDouble(this.cte.getText());
       cts=Double.parseDouble(this.cts.getText());
       ctse=Double.parseDouble(this.ctse.getText());
       cs=Double.parseDouble(this.cs.getText());
       
       double cCtte=CalcularCtte(l,m,k,h,cte);
       Ctte.setText(String.valueOf(cCtte));
       
       double cCtts=CalcularCtts(l,m,k,h,cts);
       Ctts.setText(String.valueOf(cCtts));
       
       double cCttse=CalcularCttse(l,m,k,h,ctse);
       Cttse.setText(String.valueOf(cCttse));
       
       double cCts=CalcularCts(k,cs);
       Cts.setText(String.valueOf(cCts));
       
       double cCt=CalcularCt(l,m,k,h,cte,cts,ctse,cs);
       Ct.setText(String.valueOf(cCt));
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    public static double Factorial(int a)
    {
        double b=1;
            for(int num=a;num>=1;num--)
            {
                b*=num;
            }
        return b;
    }
    
    public static double CalcularPo(double l, double m, double k)
    {
        double sumatoria=0;
            for(int ni=0;ni<=(k-1);ni++)
            {
                double factor=1/Factorial(ni);
                double elevado = pow((l/m),ni);

                double respuesta = factor*elevado;
                sumatoria=sumatoria+respuesta;
            }

        double segundaparte = 0;
            segundaparte = (1/Factorial((int)k))*(pow((l/m), (k))*((k*m)/((k*m)-l)));
        double respuestaPo=1/(sumatoria+segundaparte);//Respuesta Po
        
        return respuestaPo;
    }
    
    public static double CalcularPk(double l, double m, double k)
    {
        double parteUno=(1 / Factorial((int)k));
        double parteDos = pow((l/m), k);
        double parteTres = (k * m) / ((k * m) - l);
        double respuestaPk = parteUno * parteDos * parteTres * CalcularPo(l,m,k);//Respuesta Pk
        
        return respuestaPk;
    }
    
    public static double CalcularPne(double l, double m, double k)
    {
        double respuestaPne=1-CalcularPk(l,m,k); //Respuesta Pne
        
        return respuestaPne;
    }
    
    public static double CalcularPn(double l, double m, double k, int n)
    {
        double respuestaPn=0;
        if (n <= k)
        {
            respuestaPn = (CalcularPo(l,m,k)/ Factorial((int)n)) * pow(((l / m)), n);
        }
        else if (n > k)
        {
            respuestaPn = (1 / (Factorial((int)k) * pow(k, (n - k)))) * pow((l / m), n);
        }
        
        return respuestaPn;
    }
    
    public static double CalcularL(double l, double m, double k)
    {
        double arriba = (l * m) * pow((l/m),k);
        double abajo = Factorial((int)(k-1))*pow(((k*m)-l),2);
        double alado = l / m;

        double respuestaL = ((arriba/abajo) * CalcularPo(l,m,k)) + alado; //Respuesta L
        
        return respuestaL;
    }
    
    public static double CalcularLq(double l, double m, double k)
    {
        double arribaLq = (l * m) * pow((l / m), k)*CalcularPo(l,m,k);
        double abajoLq = Factorial((int)(k - 1)) * pow(((k * m) - l), 2);

        double respuestaLq = arribaLq / abajoLq; //Respuesta Lq
        
        return respuestaLq;
    }
    
    public static double CalcularLn(double l, double m, double k)
    {
        double respuestaLn = CalcularLq(l,m,k)/ CalcularPk(l,m,k); //Respuesta Ln
        
        return respuestaLn;
    }
    
    public static double CalcularW(double l, double m, double k)
    {
        double arribaW = m * pow((l / m), k) * CalcularPo(l,m,k);
        double abajoW = Factorial(((int)k - 1)) * pow(((k * m) - l), 2);
        double aladoW = 1 / m;

        double respuestaW = (arribaW/ abajoW)+aladoW;   //Respuesta W
        
        return respuestaW;
    }
    
    public static double CalcularWq(double l, double m, double k)
    {
        double arribaWq =m * pow((l / m), k) * CalcularPo(l,m,k);
        double abajoWq = Factorial((int)(k - 1)) * pow(((k * m) - l), 2);

        double respuestaWq = arribaWq/ abajoWq;     //Respuesta Wq
        
        return respuestaWq;
    }
    
    public static double CalcularWn(double l, double m, double k)
    {
        double respuestaWn = CalcularWq(l,m,k) / CalcularPk(l,m,k);   //Respuesta Wn
        
        return respuestaWn;
    }
    
    public static double CalcularCtte(double l, double m, double k, double h, double cte)
    {
        double respuestaCtte=(l*h*CalcularWq(l,m,k)*cte);
        respuestaCtte=Math.round(respuestaCtte*100);
        respuestaCtte=respuestaCtte/100;
        return respuestaCtte;
    }
    
    public static double CalcularCtts(double l, double m, double k, double h, double cts)
    {
        double respuestaCtts=(l*h*CalcularW(l,m,k)*cts);
        respuestaCtts=Math.round(respuestaCtts*100);
        respuestaCtts=respuestaCtts/100;
        return respuestaCtts;
    }
    
    public static double CalcularCttse(double l, double m, double k, double h, double ctse)
    {
        double respuestaCttse=(l*h*CalcularW(l,m,k)*ctse);
        respuestaCttse=Math.round(respuestaCttse*100);
        respuestaCttse=respuestaCttse/100;
        return respuestaCttse;
    }
    
    public static double CalcularCts(double k, double cs)
    {
        double respuestaCts=k*cs;
        return respuestaCts;
    }
    
    public static double CalcularCt(double l,double m,double k,double h,double cte,double cts,double ctse,double cs)
    {
        double respuestaCt=CalcularCtte(l,m,k,h,cte)+CalcularCtts(l,m,k,h,cts)+CalcularCttse(l,m,k,h,ctse)+CalcularCts(k,cs);
        respuestaCt=Math.round(respuestaCt*100);
        respuestaCt=respuestaCt/100;
        return respuestaCt;
    }
    
    public static double Probabilidad(int cb, double l, double m, double k, int n1)
    {
        double respuesta =0;
        
        if(cb==0)
        {
            for(int i=0;i<n1;i++){
                respuesta+=CalcularPn(l,m,k,i);
            }
            respuesta=1-respuesta;
        }
        else
        {
            for(int i=0;i<=n1;i++){
                respuesta+=CalcularPn(l,m,k,i);
            }
        } 
       
        return respuesta;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PICM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PICM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PICM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PICM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PICM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb;
    private javax.swing.JLabel Ct;
    private javax.swing.JLabel Cts;
    private javax.swing.JLabel Ctte;
    private javax.swing.JLabel Ctts;
    private javax.swing.JLabel Cttse;
    private javax.swing.JLabel L;
    private javax.swing.JLabel Ln;
    private javax.swing.JLabel Lq;
    private javax.swing.JLabel Num;
    private javax.swing.JLabel Pk;
    private javax.swing.JLabel Pn;
    private javax.swing.JLabel Pne;
    private javax.swing.JLabel Po;
    private javax.swing.JLabel W;
    private javax.swing.JLabel Wn;
    private javax.swing.JLabel Wq;
    private javax.swing.JTextField cs;
    private javax.swing.JTextField cte;
    private javax.swing.JTextField cts;
    private javax.swing.JTextField ctse;
    private javax.swing.JTextField horas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField k;
    private javax.swing.JTextField lambda;
    private javax.swing.JTextField mu;
    private javax.swing.JTextField n;
    private javax.swing.JTextField n1;
    // End of variables declaration//GEN-END:variables
}
