
import static java.lang.Math.pow;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KEVIN FABRICIO
 */
public class PFCM extends javax.swing.JFrame {

    /**
     * Creates new form PFCM
     */
    public PFCM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lambda = new javax.swing.JTextField();
        mu = new javax.swing.JTextField();
        k = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox<>();
        n1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Num = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cte = new javax.swing.JTextField();
        cts = new javax.swing.JTextField();
        ctse = new javax.swing.JTextField();
        cs = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        h = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Ctte = new javax.swing.JLabel();
        Ctts = new javax.swing.JLabel();
        Cttse = new javax.swing.JLabel();
        Cts = new javax.swing.JLabel();
        Ct = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Po = new javax.swing.JLabel();
        Pn = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        Lq = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Ln = new javax.swing.JLabel();
        W = new javax.swing.JLabel();
        Wn = new javax.swing.JLabel();
        Wq = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Pe = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        poblacion = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PFCM");

        jLabel2.setText("Lambda :");

        jLabel3.setText("Mu :");

        jLabel4.setText("K :");

        jLabel5.setText("N :");

        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">=", "<=", " " }));

        jLabel6.setText("PROBABILIDAD");

        jLabel7.setText("Respuesta :");

        Num.setText("jLabel8");

        jLabel8.setText("COSTOS");

        jLabel9.setText("Costo Diario T Cola CTE :");

        jLabel10.setText("Costo Diario T Sistema CTS :");

        jLabel11.setText("Costo Diario T Servicio CTSE :");

        jLabel12.setText("Costo Servidor CS :");

        cts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctsActionPerformed(evt);
            }
        });

        ctse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctseActionPerformed(evt);
            }
        });

        jLabel13.setText("Horas :");

        jLabel14.setText("CTTE :");

        jLabel15.setText("CTTS :");

        jLabel16.setText("CTTSE :");

        jLabel17.setText("CTS :");

        jLabel18.setText("CT :");

        Ctte.setText("jLabel19");

        Ctts.setText("jLabel20");

        Cttse.setText("jLabel21");

        Cts.setText("jLabel22");

        Ct.setText("jLabel23");

        jLabel19.setText("Po :");

        jLabel20.setText("Pn :");

        jLabel21.setText("L :");

        jLabel22.setText("Lq :");

        Po.setText("jLabel23");

        Pn.setText("jLabel24");

        L.setText("jLabel25");

        Lq.setText("jLabel26");

        jLabel27.setText("Ln :");

        jLabel28.setText("W :");

        jLabel29.setText("Wn :");

        jLabel30.setText("Wq :");

        Ln.setText("jLabel31");

        W.setText("jLabel32");

        Wn.setText("jLabel33");

        Wq.setText("jLabel34");

        jLabel23.setText("Pe :");

        Pe.setText("jLabel24");

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel24.setText("M :");

        jButton2.setText("CAL COSTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addContainerGap(551, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(n1)
                                        .addGap(116, 116, 116)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(97, 97, 97))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Po)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel27))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Pn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel28))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Lq)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel30))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(L)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel29)))))
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Num)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ctse, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(cts)
                                    .addComponent(cte)
                                    .addComponent(cs))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(168, 168, 168)
                                        .addComponent(jLabel14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mu)
                                    .addComponent(k)
                                    .addComponent(n)
                                    .addComponent(lambda, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(poblacion))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Ctte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ct)
                                        .addGap(9, 9, 9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Ctts)
                                            .addComponent(Cttse)
                                            .addComponent(Cts)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Ln)
                                                .addGap(60, 60, 60)
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Pe))
                                            .addComponent(W)
                                            .addComponent(Wn)
                                            .addComponent(Wq))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Po)
                    .addComponent(jLabel27)
                    .addComponent(Ln)
                    .addComponent(jLabel23)
                    .addComponent(Pe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(Pn)
                    .addComponent(jLabel28)
                    .addComponent(W))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(L)
                    .addComponent(jLabel29)
                    .addComponent(Wn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(Lq)
                    .addComponent(jLabel30)
                    .addComponent(Wq))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Num))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(Ctte)
                    .addComponent(Ct))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ctse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Ctts))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(Cttse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Cts))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kActionPerformed

    private void ctsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctsActionPerformed

    private void ctseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       double l=0;
       double m=0;
       double M=0;
       double k=0;
       int  n=0,n1=0, cb=0; 

       l=Double.parseDouble(this.lambda.getText());
       m=Double.parseDouble(this.mu.getText());
       M=Double.parseDouble(this.poblacion.getText());
       k=Double.parseDouble(this.k.getText());
       n=Integer.parseInt(this.n.getText());
       n1=Integer.parseInt(this.n1.getText());
       cb=this.cb.getSelectedIndex();
       
        double cPo=CalcularPo(l,m,M,k);
       Po.setText(String.valueOf(cPo));
       
       double cPn=CalcularPn(l,m,M,n,k);
       Pn.setText(String.valueOf(cPn));
       
       double cL=CalcularL(l,m,M,k);
       L.setText(String.valueOf(cL));
       
       double cLq=CalcularLq(l,m,M,k);
       Lq.setText(String.valueOf(cLq));
       
       double cLn=CalcularLn(l,m,M,k);
       Ln.setText(String.valueOf(cLn));
       
       double cW=CalcularW(l,m,M,k);
       W.setText(String.valueOf(cW));
       
       double cWq=CalcularWq(l,m,M,k);
       Wq.setText(String.valueOf(cWq));
       
       double cWn=CalcularWn(l,m,M,k);
       Wn.setText(String.valueOf(cWn));
            
       double cP=Probabilidad(cb,l,m,M,n1,k);
       Num.setText(String.valueOf(cP));
       
       double cPe=CalcularPe(l,m,M,k);
       Pe.setText(String.valueOf(cPe));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       double l=0;
       double m=0;
       double M=0;
       double h=0, cte=0, cts=0, ctse=0, cs=0,k=0;
       
       l=Double.parseDouble(this.lambda.getText());
       m=Double.parseDouble(this.mu.getText());
       M=Double.parseDouble(this.poblacion.getText());
       h=Double.parseDouble(this.h.getText());
       cte=Double.parseDouble(this.cte.getText());
       cts=Double.parseDouble(this.cts.getText());
       ctse=Double.parseDouble(this.ctse.getText());
       cs=Double.parseDouble(this.cs.getText());
       
       double cCtte=CalcularCtte(l,m,M,h,cte,k);
       Ctte.setText(String.valueOf(cCtte));
       
       double cCtts=CalcularCtts(l,m,M,h,cts,k);
       Ctts.setText(String.valueOf(cCtts));
       
       double cCttse=CalcularCttse(l,m,M,h,ctse,k);
       Cttse.setText(String.valueOf(cCttse));
       
       double cCts=CalcularCts(k,cs);
       Cts.setText(String.valueOf(cCts));
       
       double cCt=CalcularCt(l,m,M,h,cte,cts,ctse,cs,k);
       Ct.setText(String.valueOf(cCt));
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public static double Factorial(int a)
    {
        double b = 1;

        for (int num = a; num >= 1; num--)
        {
            b *= num;
        }
        return b;
    }
    
    public static double CalcularPo(double l, double m, double M, double k)
    {
        double sumatoria = 0,sumatoria1=0;

        for (int n = 0; n <= M; n++)
        {
            double respuesta1 = (Factorial((int)M) / Factorial((int)(M - n))*Factorial((int)n)) * pow((l / m), n);
            sumatoria = sumatoria + respuesta1;
            
            double respuesta2 = (Factorial((int)M) / Factorial((int)(M - n))*Factorial((int)k)*pow(k,(n-k))) * pow((l / m), k);
            sumatoria1 = sumatoria1 + respuesta2;
        }

        double respuestaPo = 1 / (sumatoria+sumatoria1);
        respuestaPo=Math.round(respuestaPo *10000);
        respuestaPo=respuestaPo/10000;
        return respuestaPo;
    }
    
    public static double CalcularPn(double l, double m, double M, int n, double k)
    {
        double respuestaPn = 0;
        if (n>0 && n <= k)
        {
            respuestaPn = (Factorial((int)M) / Factorial((int)(M - n))) * pow((l / m), n) * CalcularPo(l,m,M,k);
        }
        else if (n >= k && n<=M)
        {
            respuestaPn = (Factorial((int)M) / Factorial((int)(M - n))*Factorial((int)k)*pow(k,(n-k))) * pow((l / m), k)* CalcularPo(l,m,M,k);
        }
        respuestaPn=Math.round(respuestaPn *10000);
        respuestaPn=respuestaPn/10000;
        return respuestaPn;
    }
    
    public static double CalcularPe(double l, double m, double M, double k)
    {
    double sumatoria = 0;

        for (int n = (int)k; n <= M; n++)
        {            
            double respuesta = CalcularPo(l,m,M,k)* (Factorial((int)M) / (Factorial(((int)M - n)) * Factorial((int)k) * (pow(k, (n - k))))) * pow((l / m), n);
            sumatoria = sumatoria + respuesta;
        }
        double respuestaPe = sumatoria;
        respuestaPe=Math.round(respuestaPe *10000);
        respuestaPe=respuestaPe/10000;
        return respuestaPe;
    }
    
    public static double CalcularL(double l, double m, double M, double k)
    {
        double sumatoria = 0,sumatoria1=0, sumatoria2=0;

        for (int n = 0; n <= k-1; n++)
        {
            double PnL1 = CalcularPo(l,m,M,k)*(Factorial((int)M) / (Factorial(((int)M - n)) * Factorial(n))) * pow((l / m), n);
            double respuesta1=n*PnL1;
            sumatoria = sumatoria + respuesta1; 
        }
 
        for (int n = (int)k; n <= M; n++)
        {
            double PnL2 = CalcularPo(l,m,M,k)*(Factorial((int)M) / (Factorial(((int)M - n)) * Factorial((int)k) * (pow(k, (n - k))))) * pow((l / m), n);
            double respuesta2=(n - k) * PnL2;
            sumatoria1 = sumatoria1 + respuesta2;       
        }
        
        for (int n = 0; n <= k-1; n++)
        {
            double PnL3 = CalcularPo(l,m,M,k)* (Factorial((int)M) / (Factorial(((int)M - n)) * Factorial(n))) * pow((l / m), n);
            sumatoria2 = sumatoria2+PnL3;
        }
        
        double respuestaL = sumatoria+sumatoria1+(k*(1-sumatoria2));
        respuestaL=Math.round(respuestaL *10000);
        respuestaL=respuestaL/10000;
        return respuestaL;
    }
    
    public static double CalcularLq(double l, double m, double M, double k)
    {
        double sumatoria = 0;
        for (int n = (int)k; n <= M; n++)
        {
            double PnL2 = CalcularPo(l,m,M,k)*(Factorial((int)M) / (Factorial(((int)M - n)) * Factorial((int)k) * (pow(k, (n - k))))) * pow((l / m), n);
            double respuesta=(n-k)*PnL2;
            sumatoria = sumatoria + respuesta;       
        }
        double respuestaLq = sumatoria;
        respuestaLq=Math.round(respuestaLq *10000);
        respuestaLq=respuestaLq/10000;
        return respuestaLq;
    }
    
    public static double CalcularLn(double l, double m, double M, double k)
    {
        double respuestaLn = CalcularLq(l,m,M,k) / CalcularPe(l,m,M,k);
        respuestaLn=Math.round(respuestaLn *10000);
        respuestaLn=respuestaLn/10000;
        return respuestaLn;
    }
    
    public static double CalcularWq(double l, double m, double M, double k)
    {
        double Lq=CalcularLq(l,m,M,k);
        double L=CalcularL(l,m,M,k);
        double respuestaWq = Lq/((M-L)*l);
        respuestaWq=Math.round(respuestaWq *10000);
        respuestaWq=respuestaWq/10000;
        return respuestaWq;
    }
    
    public static double CalcularW(double l, double m, double M,double k)
    {
        double respuestaW = CalcularWq(l,m,M,k) + (1/m);
        respuestaW=Math.round(respuestaW *10000);
        respuestaW=respuestaW/10000;
        return respuestaW;
    }
    
    public static double CalcularWn(double l, double m, double M, double k)
    {
        double respuestaWn = CalcularWq(l,m,M,k) / CalcularPe(l,m,M,k);
        respuestaWn=Math.round(respuestaWn *10000);
        respuestaWn=respuestaWn/10000;
        return respuestaWn;
    }
    
     public static double CalcularCtte(double l, double m, double k, double h, double cte, double k1)
    {
        double respuestaCtte=(l*h*CalcularWq(l,m,k,k1)*cte);
        respuestaCtte=Math.round(respuestaCtte*100);
        respuestaCtte=respuestaCtte/100;
        return respuestaCtte;
    }
    
    public static double CalcularCtts(double l, double m, double k, double h, double cts,double k1)
    {
        double respuestaCtts=(l*h*CalcularW(l,m,k,k1)*cts);
        respuestaCtts=Math.round(respuestaCtts*100);
        respuestaCtts=respuestaCtts/100;
        return respuestaCtts;
    }
    
    public static double CalcularCttse(double l, double m, double k, double h, double ctse,double k1)
    {
        double respuestaCttse=(l*h*CalcularW(l,m,k,k1)*ctse);
        respuestaCttse=Math.round(respuestaCttse*100);
        respuestaCttse=respuestaCttse/100;
        return respuestaCttse;
    }
    
    public static double CalcularCts(double k1, double cs)
    {
        double respuestaCts=k1*cs;
        return respuestaCts;
    }
    
    public static double CalcularCt(double l,double m,double k,double h,double cte,double cts,double ctse,double cs,double k1)
    {
        double respuestaCt=CalcularCtte(l,m,k,h,cte,k1)+CalcularCtts(l,m,k,h,cts,k1)+CalcularCttse(l,m,k,h,ctse,k1)+CalcularCts(k1,cs);
        respuestaCt=Math.round(respuestaCt*100);
        respuestaCt=respuestaCt/100;
        return respuestaCt;
    }
    
    public static double Probabilidad(int cb, double l, double m, double k, int n1,double k1)
    {
        double respuesta =0;
        
        if(cb==0)
        {
            for(int i=0;i<n1;i++){
                respuesta+=CalcularPn(l,m,k,i,k1);
            }
            respuesta=1-respuesta;
        }
        else
        {
            for(int i=0;i<=n1;i++){
                respuesta+=CalcularPn(l,m,k,i,k1);
            }
        } 
        respuesta=Math.round(respuesta*100);
        respuesta=respuesta/100;
        return respuesta;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PFCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PFCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PFCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PFCM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PFCM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ct;
    private javax.swing.JLabel Cts;
    private javax.swing.JLabel Ctte;
    private javax.swing.JLabel Ctts;
    private javax.swing.JLabel Cttse;
    private javax.swing.JLabel L;
    private javax.swing.JLabel Ln;
    private javax.swing.JLabel Lq;
    private javax.swing.JLabel Num;
    private javax.swing.JLabel Pe;
    private javax.swing.JLabel Pn;
    private javax.swing.JLabel Po;
    private javax.swing.JLabel W;
    private javax.swing.JLabel Wn;
    private javax.swing.JLabel Wq;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextField cs;
    private javax.swing.JTextField cte;
    private javax.swing.JTextField cts;
    private javax.swing.JTextField ctse;
    private javax.swing.JTextField h;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField k;
    private javax.swing.JTextField lambda;
    private javax.swing.JTextField mu;
    private javax.swing.JTextField n;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField poblacion;
    // End of variables declaration//GEN-END:variables
}
