
import static java.lang.Math.pow;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KEVIN FABRICIO
 */
public class PFCS extends javax.swing.JFrame {

    /**
     * Creates new form PFCS
     */
    public PFCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lambda = new javax.swing.JTextField();
        miu = new javax.swing.JTextField();
        poblacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Po = new javax.swing.JLabel();
        Pn = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        Lq = new javax.swing.JLabel();
        Ln = new javax.swing.JLabel();
        W = new javax.swing.JLabel();
        Wn = new javax.swing.JLabel();
        Wq = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cte = new javax.swing.JTextField();
        cts = new javax.swing.JTextField();
        ctse = new javax.swing.JTextField();
        cs = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Ctte = new javax.swing.JLabel();
        Ctts = new javax.swing.JLabel();
        Cttse = new javax.swing.JLabel();
        Cts = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Ct = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        n1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Num = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Pe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PFCS");

        jLabel2.setText("Lambda :");

        jLabel3.setText("Miu :");

        jLabel4.setText("Poblacion M :");

        poblacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poblacionActionPerformed(evt);
            }
        });

        jLabel5.setText("Po :");

        jLabel6.setText("Pn :");

        jLabel7.setText("L :");

        jLabel8.setText("Lq :");

        jLabel9.setText("Ln :");

        jLabel10.setText("W :");

        jLabel11.setText("Wn :");

        jLabel12.setText("Wq :");

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Po.setText("jLabel13");

        Pn.setText("jLabel14");

        L.setText("jLabel15");

        Lq.setText("jLabel16");

        Ln.setText("jLabel17");

        W.setText("jLabel18");

        Wn.setText("jLabel19");

        Wq.setText("jLabel20");

        jLabel21.setText("Costo Diario T Cola CTE :");

        jLabel22.setText("Costo Diario T Sistema CTS :");

        jLabel23.setText("Costo Diario T Servicio CTSE :");

        jLabel24.setText("Costo Servidor CS :");

        jLabel25.setText("Horas :");

        cts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctsActionPerformed(evt);
            }
        });

        cs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csActionPerformed(evt);
            }
        });

        jLabel26.setText("COSTOS");

        jLabel27.setText("CTTE :");

        jLabel28.setText("CTTS :");

        jLabel29.setText("CTTSE :");

        jLabel30.setText("CTS :");

        Ctte.setText("jLabel31");

        Ctts.setText("jLabel32");

        Cttse.setText("jLabel33");

        Cts.setText("jLabel34");

        jLabel35.setText("CT :");

        Ct.setText("jLabel36");

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">=", "<=", " " }));

        jLabel13.setText("PROBABILIDAD");

        jLabel14.setText("Respuesta :");

        Num.setText("jLabel15");

        jLabel15.setText("N :");

        jButton2.setText("CAL COSTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Pe :");

        Pe.setText("jLabel17");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(n, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(poblacion, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(miu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lambda, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L)
                    .addComponent(Pn)
                    .addComponent(Po)
                    .addComponent(Lq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Wn))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Wq)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ln))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(W)))
                .addGap(135, 135, 135))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ctts)
                                    .addComponent(Cttse)
                                    .addComponent(Cts)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Ctte)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ct))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(128, 128, 128)))
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel22)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(n1)
                                    .addComponent(Num))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cs)
                                    .addComponent(cts)
                                    .addComponent(ctse)
                                    .addComponent(cte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pe)
                        .addGap(214, 214, 214))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Po)
                    .addComponent(jLabel9)
                    .addComponent(Ln))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(miu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Pn)
                    .addComponent(jLabel10)
                    .addComponent(W))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(L)
                        .addComponent(jLabel11)
                        .addComponent(Wn)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Lq)
                            .addComponent(jLabel12)
                            .addComponent(Wq)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel16)
                    .addComponent(Pe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Num))
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(ctse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(cs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(Ctte)
                            .addComponent(jLabel35)
                            .addComponent(Ct))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(Ctts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(Cttse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(Cts))))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poblacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poblacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poblacionActionPerformed

    private void ctsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctsActionPerformed

    private void csActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       double l=0;
       double m=0;
       double M=0;
       int  n=0,n1=0, cb=0;
       
       l=Double.parseDouble(this.lambda.getText());
       m=Double.parseDouble(this.miu.getText());
       M=Double.parseDouble(this.poblacion.getText());
       n=Integer.parseInt(this.n.getText());
       n1=Integer.parseInt(this.n1.getText());
       cb=this.cb.getSelectedIndex();
       
       double cPo=CalcularPo(l,m,M);
       Po.setText(String.valueOf(cPo));
       
       double cPe=CalcularPe(l,m,M);
       Pe.setText(String.valueOf(cPe));
       
       double cPn=CalcularPn(l,m,M,n);
       Pn.setText(String.valueOf(cPn));
       
       double cL=CalcularL(l,m,M);
       L.setText(String.valueOf(cL));
       
       double cLq=CalcularLq(l,m,M);
       Lq.setText(String.valueOf(cLq));
       
       double cLn=CalcularLn(l,m,M);
       Ln.setText(String.valueOf(cLn));
       
       double cW=CalcularW(l,m,M);
       W.setText(String.valueOf(cW));
       
       double cWq=CalcularWq(l,m,M);
       Wq.setText(String.valueOf(cWq));
       
       double cWn=CalcularWn(l,m,M);
       Wn.setText(String.valueOf(cWn));
              
       double cP=Probabilidad(cb,l,m,M,n1);
       Num.setText(String.valueOf(cP));
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       double l=0;
       double m=0;
       double M=0;
       double h=0, cte=0, cts=0, ctse=0, cs=0;
       int k=1;
       
       l=Double.parseDouble(this.lambda.getText());
       m=Double.parseDouble(this.miu.getText());
       M=Double.parseDouble(this.poblacion.getText());
       h=Double.parseDouble(this.h.getText());
       cte=Double.parseDouble(this.cte.getText());
       cts=Double.parseDouble(this.cts.getText());
       ctse=Double.parseDouble(this.ctse.getText());
       cs=Double.parseDouble(this.cs.getText());
       
       double cCtte=CalcularCtte(l,m,M,h,cte);
       Ctte.setText(String.valueOf(cCtte));
       
       double cCtts=CalcularCtts(l,m,M,h,cts);
       Ctts.setText(String.valueOf(cCtts));
       
       double cCttse=CalcularCttse(l,m,M,h,ctse);
       Cttse.setText(String.valueOf(cCttse));
       
       double cCts=CalcularCts(k,cs);
       Cts.setText(String.valueOf(cCts));
       
       double cCt=CalcularCt(l,m,M,h,cte,cts,ctse,cs);
       Ct.setText(String.valueOf(cCt));
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    public static double Factorial(int a)
    {
        double b = 1;

        for (int num = a; num >= 1; num--)
        {
            b *= num;
        }
        return b;
    }
    
    public static double CalcularPo(double l, double m, double M)
    {
        double sumatoria = 0;

        for (int n = 0; n <= M; n++)
        {
            double respuesta = (Factorial((int)M) / Factorial((int)(M - n))) * pow((l / m), n);
            sumatoria = sumatoria + respuesta;
        }

        double respuestaPo = 1 / sumatoria;
        respuestaPo=Math.round(respuestaPo *10000);
        respuestaPo=respuestaPo/10000;
        return respuestaPo;
    }
    
    public static double CalcularPn(double l, double m, double M, int n)
    {
        double respuestaPn = (Factorial((int)M) / Factorial((int)(M - n))) * pow((l / m), n) * CalcularPo(l,m,M);
        respuestaPn=Math.round(respuestaPn *10000);
        respuestaPn=respuestaPn/10000;
        return respuestaPn;
    }
    
    public static double CalcularL(double l, double m, double M)
    {
        double respuestaL = M-(m/l)*(1-CalcularPo(l,m,M));
        respuestaL=Math.round(respuestaL *10000);
        respuestaL=respuestaL/10000;
        return respuestaL;
    }
    
    public static double CalcularLq(double l, double m, double M)
    {
        double respuestaLq = M - ((l+m) / l) * (1 - CalcularPo(l,m,M));
        respuestaLq=Math.round(respuestaLq *10000);
        respuestaLq=respuestaLq/10000;
        return respuestaLq;
    }
    
    public static double CalcularLn(double l, double m, double M)
    {
        double respuestaLn = CalcularLq(l,m,M) / (1-CalcularPo(l,m,M));
        respuestaLn=Math.round(respuestaLn *10000);
        respuestaLn=respuestaLn/10000;
        return respuestaLn;
    }
    
    public static double CalcularWq(double l, double m, double M)
    {
        double Lq=CalcularLq(l,m,M);
        double L=CalcularL(l,m,M);
        double respuestaWq = Lq/((M-L)*l);
        respuestaWq=Math.round(respuestaWq *10000);
        respuestaWq=respuestaWq/10000;
        return respuestaWq;
    }
    
    public static double CalcularW(double l, double m, double M)
    {
        double respuestaW = CalcularWq(l,m,M) + (1/m);
        respuestaW=Math.round(respuestaW *10000);
        respuestaW=respuestaW/10000;
        return respuestaW;
    }
    
    public static double CalcularWn(double l, double m, double M)
    {
        double respuestaWn = CalcularWq(l,m,M) / (1 - CalcularPo(l,m,M));
        respuestaWn=Math.round(respuestaWn *10000);
        respuestaWn=respuestaWn/10000;
        return respuestaWn;
    }
    
    public static double CalcularCtte(double l, double m, double k, double h, double cte)
    {
        double respuestaCtte=(l*h*CalcularWq(l,m,k)*cte);
        respuestaCtte=Math.round(respuestaCtte*100);
        respuestaCtte=respuestaCtte/100;
        return respuestaCtte;
    }
    
    public static double CalcularCtts(double l, double m, double k, double h, double cts)
    {
        double respuestaCtts=(l*h*CalcularW(l,m,k)*cts);
        respuestaCtts=Math.round(respuestaCtts*100);
        respuestaCtts=respuestaCtts/100;
        return respuestaCtts;
    }
    
    public static double CalcularCttse(double l, double m, double k, double h, double ctse)
    {
        double respuestaCttse=(l*h*CalcularW(l,m,k)*ctse);
        respuestaCttse=Math.round(respuestaCttse*100);
        respuestaCttse=respuestaCttse/100;
        return respuestaCttse;
    }
    
    public static double CalcularCts(double k, double cs)
    {
        double respuestaCts=k*cs;
        return respuestaCts;
    }
    
    public static double CalcularCt(double l,double m,double k,double h,double cte,double cts,double ctse,double cs)
    {
        double respuestaCt=CalcularCtte(l,m,k,h,cte)+CalcularCtts(l,m,k,h,cts)+CalcularCttse(l,m,k,h,ctse)+CalcularCts(k,cs);
        respuestaCt=Math.round(respuestaCt*100);
        respuestaCt=respuestaCt/100;
        return respuestaCt;
    }
    
    public static double CalcularPe(double l, double m, double M)
    {
        double respuesta=1-CalcularPo(l,m,M);
        return respuesta;
    }
    
    public static double Probabilidad(int cb, double l, double m, double k, int n1)
    {
        double respuesta =0;
        
        if(cb==0)
        {
            for(int i=0;i<n1;i++){
                respuesta+=CalcularPn(l,m,k,i);
            }
            respuesta=1-respuesta;
        }
        else
        {
            for(int i=0;i<=n1;i++){
                respuesta+=CalcularPn(l,m,k,i);
            }
        } 
        
        return respuesta;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PFCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PFCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PFCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PFCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PFCS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ct;
    private javax.swing.JLabel Cts;
    private javax.swing.JLabel Ctte;
    private javax.swing.JLabel Ctts;
    private javax.swing.JLabel Cttse;
    private javax.swing.JLabel L;
    private javax.swing.JLabel Ln;
    private javax.swing.JLabel Lq;
    private javax.swing.JLabel Num;
    private javax.swing.JLabel Pe;
    private javax.swing.JLabel Pn;
    private javax.swing.JLabel Po;
    private javax.swing.JLabel W;
    private javax.swing.JLabel Wn;
    private javax.swing.JLabel Wq;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextField cs;
    private javax.swing.JTextField cte;
    private javax.swing.JTextField cts;
    private javax.swing.JTextField ctse;
    private javax.swing.JTextField h;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lambda;
    private javax.swing.JTextField miu;
    private javax.swing.JTextField n;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField poblacion;
    // End of variables declaration//GEN-END:variables
}
