
import static java.lang.Math.pow;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KEVIN FABRICIO
 */
public class PICS extends javax.swing.JFrame {

    /**
     * Creates new form PICS
     */
    public PICS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lambda = new javax.swing.JTextField();
        mu = new javax.swing.JTextField();
        cb = new javax.swing.JComboBox<>();
        n1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Num = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cte = new javax.swing.JTextField();
        cts = new javax.swing.JTextField();
        ctse = new javax.swing.JTextField();
        cs = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        h = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Ro = new javax.swing.JLabel();
        Po = new javax.swing.JLabel();
        Pn = new javax.swing.JLabel();
        Lq = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Wq = new javax.swing.JLabel();
        W = new javax.swing.JLabel();
        Ln = new javax.swing.JLabel();
        Wn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Ctte = new javax.swing.JLabel();
        Ctts = new javax.swing.JLabel();
        Cttse = new javax.swing.JLabel();
        Cts = new javax.swing.JLabel();
        Ct = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PICS");

        jLabel2.setText("Lambda :");

        jLabel3.setText("Mu :");

        mu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muActionPerformed(evt);
            }
        });

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">=", "<=", " " }));

        jLabel4.setText("Respuesta :");

        Num.setText("jLabel5");

        jLabel5.setText("PROBABILIDAD");

        jLabel6.setText("COSTOS");

        jLabel7.setText("Costo Diario T Cola CTE :");

        jLabel8.setText("Costo Diario T Sistema CTS :");

        jLabel9.setText("Costo Diario T Servicio CTSE :");

        jLabel10.setText("Costo Servidor CS :");

        ctse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctseActionPerformed(evt);
            }
        });

        jLabel11.setText("Horas :");

        jLabel12.setText("Ro :");

        jLabel13.setText("Po :");

        jLabel14.setText("Pn :");

        jLabel15.setText("Lq :");

        jLabel16.setText("L :");

        Ro.setText("jLabel17");

        Po.setText("jLabel18");

        Pn.setText("jLabel19");

        Lq.setText("jLabel20");

        L.setText("jLabel21");

        jLabel22.setText("Wq :");

        jLabel23.setText("W :");

        jLabel24.setText("Ln :");

        jLabel25.setText("Wn :");

        Wq.setText("jLabel26");

        W.setText("jLabel27");

        Ln.setText("jLabel28");

        Wn.setText("jLabel29");

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel17.setText("CTTE :");

        jLabel18.setText("CTTS :");

        jLabel19.setText("CTTSE :");

        jLabel20.setText("CTS :");

        jLabel21.setText("CT :");

        Ctte.setText("jLabel26");

        Ctts.setText("jLabel27");

        Cttse.setText("jLabel28");

        Cts.setText("jLabel29");

        Ct.setText("jLabel30");

        jButton2.setText("CAL COSTOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel26.setText("N :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Num)
                        .addGap(86, 86, 86)
                        .addComponent(jButton1))
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(L))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lambda, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(mu)
                                            .addComponent(n))
                                        .addGap(88, 88, 88)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)))
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ro)
                                    .addComponent(Po)
                                    .addComponent(Pn)
                                    .addComponent(Lq))))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Wq)
                            .addComponent(W)
                            .addComponent(Ln)
                            .addComponent(Wn)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ctse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(cts, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cte, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cs))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Ctte))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Ctts)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Cts)
                                            .addComponent(Ct)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cttse)))
                                .addGap(1, 1, 1)))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(Ro)
                    .addComponent(jLabel22)
                    .addComponent(Wq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(Po)
                    .addComponent(jLabel23)
                    .addComponent(W))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Pn)
                    .addComponent(jLabel24)
                    .addComponent(Ln))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Lq)
                    .addComponent(jLabel25)
                    .addComponent(Wn)
                    .addComponent(jLabel26)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Num)
                    .addComponent(jButton1))
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(Ctte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ctse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(Ctts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Cttse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(Ct))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void muActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muActionPerformed

    private void ctseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       double l=0;
       double m=0;
       int n=0,n1=0, cb=0;
       
       l=Double.parseDouble(this.lambda.getText());
       m=Double.parseDouble(this.mu.getText());
       n=Integer.parseInt(this.n.getText());
       n1=Integer.parseInt(this.n1.getText());
       cb=this.cb.getSelectedIndex();
       
       double cRo=CalcularRo(l,m);
       Ro.setText(String.valueOf(cRo));
       
       double cPo=CalcularPo(l,m);
       Po.setText(String.valueOf(cPo));
              
       double cPn=CalcularPn(l,m,n);
       Pn.setText(String.valueOf(cPn));
              
       double cL=CalcularL(l,m);
       L.setText(String.valueOf(cL));
       
       double cLq=CalcularLq(l,m);
       Lq.setText(String.valueOf(cLq));
       
       double cLn=CalcularLn(l,m);
       Ln.setText(String.valueOf(cLn));
       
       double cW=CalcularW(l,m);
       W.setText(String.valueOf(cW));
       
       double cWq=CalcularWq(l,m);
       Wq.setText(String.valueOf(cWq));
       
       double cWn=CalcularWn(l,m);
       Wn.setText(String.valueOf(cWn));
       
       double cP=Probabilidad(cb,l,m,n1);
       Num.setText(String.valueOf(cP));
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       double l=0;
       double m=0,k=1;
       double h=0, cte=0, cts=0, ctse=0, cs=0;
              
       l=Double.parseDouble(this.lambda.getText());
       m=Double.parseDouble(this.mu.getText());
       h=Double.parseDouble(this.h.getText());
       cte=Double.parseDouble(this.cte.getText());
       cts=Double.parseDouble(this.cts.getText());
       ctse=Double.parseDouble(this.ctse.getText());
       cs=Double.parseDouble(this.cs.getText());
       
       double cCtte=CalcularCtte(l,m,k,h,cte);
       Ctte.setText(String.valueOf(cCtte));
       
       double cCtts=CalcularCtts(l,m,k,h,cts);
       Ctts.setText(String.valueOf(cCtts));
       
       double cCttse=CalcularCttse(l,m,k,h,ctse);
       Cttse.setText(String.valueOf(cCttse));
       
       double cCts=CalcularCts(k,cs);
       Cts.setText(String.valueOf(cCts));
       
       double cCt=CalcularCt(l,m,k,h,cte,cts,ctse,cs);
       Ct.setText(String.valueOf(cCt));
    }//GEN-LAST:event_jButton2ActionPerformed

    public static double CalcularRo(double l, double m)
    {
        double respuestaRo=l/m;
        respuestaRo=Math.round(respuestaRo*10000);
        respuestaRo=respuestaRo/10000;
        return respuestaRo;
    }
    
    public static double CalcularPo(double l, double m)
    {
        double respuestaPo=1-(l/m);
        respuestaPo=Math.round(respuestaPo*10000);
        respuestaPo=respuestaPo/10000;
        return respuestaPo;
    }
    
    public static double CalcularPn(double l, double m, int n)
    {
        double respuestaPn=CalcularPo(l,m)*pow((l/m),n);
        respuestaPn=Math.round(respuestaPn*10000);
        respuestaPn=respuestaPn/10000;
        return respuestaPn;
    }
    
    public static double CalcularLq(double l, double m)
    {
        double respuestaLq=pow(l,2)/(m*(m-l));
        respuestaLq=Math.round(respuestaLq*10000);
        respuestaLq=respuestaLq/10000;
        return respuestaLq;
    }
    
    public static double CalcularL(double l, double m)
    {
        double respuestaL=(l/(m-l));
        respuestaL=Math.round(respuestaL*10000);
        respuestaL=respuestaL/10000;
        return respuestaL;
    }
    
    public static double CalcularLn(double l, double m)
    {
        double respuestaLn=CalcularL(l,m);
        respuestaLn=Math.round(respuestaLn*10000);
        respuestaLn=respuestaLn/10000;
        return respuestaLn;
    }
    
    public static double CalcularWq(double l, double m)
    {
        double respuestaWq=l/(m*(m-l));
        respuestaWq=Math.round(respuestaWq*10000);
        respuestaWq=respuestaWq/10000;
        return respuestaWq;
    }
    
    public static double CalcularW(double l, double m)
    {
        double respuestaW=(1/(m-l));
        respuestaW=Math.round(respuestaW*10000);
        respuestaW=respuestaW/10000;
        return respuestaW;
    }
    
    public static double CalcularWn(double l, double m)
    {
        double respuestaWn=CalcularW(l,m);
        respuestaWn=Math.round(respuestaWn*10000);
        respuestaWn=respuestaWn/10000;
        return respuestaWn;
    }
    
    public static double Probabilidad(int cb, double l, double m,  int n1)
    {
        double respuesta =0;
        
        if(cb==0)
        {
            for(int i=0;i<n1;i++){
                respuesta+=CalcularPn(l,m,i);
            }
            respuesta=1-respuesta;
        }
        else
        {
            for(int i=0;i<=n1;i++){
                respuesta+=CalcularPn(l,m,i);
            }
        } 
        
        return respuesta;
    }
    
     public static double CalcularCtte(double l, double m, double k, double h, double cte)
    {
        double respuestaCtte=(l*h*CalcularWq(l,m)*cte);
        respuestaCtte=Math.round(respuestaCtte*100);
        respuestaCtte=respuestaCtte/100;
        return respuestaCtte;
    }
    
    public static double CalcularCtts(double l, double m, double k, double h, double cts)
    {
        double respuestaCtts=(l*h*CalcularW(l,m)*cts);
        respuestaCtts=Math.round(respuestaCtts*100);
        respuestaCtts=respuestaCtts/100;
        return respuestaCtts;
    }
    
    public static double CalcularCttse(double l, double m, double k, double h, double ctse)
    {
        double respuestaCttse=(l*h*CalcularW(l,m)*ctse);
        respuestaCttse=Math.round(respuestaCttse*100);
        respuestaCttse=respuestaCttse/100;
        return respuestaCttse;
    }
    
    public static double CalcularCts(double k, double cs)
    {
        double respuestaCts=k*cs;
        return respuestaCts;
    }
    
    public static double CalcularCt(double l,double m,double k,double h,double cte,double cts,double ctse,double cs)
    {
        double respuestaCt=CalcularCtte(l,m,k,h,cte)+CalcularCtts(l,m,k,h,cts)+CalcularCttse(l,m,k,h,ctse)+CalcularCts(k,cs);
        respuestaCt=Math.round(respuestaCt*100);
        respuestaCt=respuestaCt/100;
        return respuestaCt;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PICS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PICS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PICS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PICS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PICS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ct;
    private javax.swing.JLabel Cts;
    private javax.swing.JLabel Ctte;
    private javax.swing.JLabel Ctts;
    private javax.swing.JLabel Cttse;
    private javax.swing.JLabel L;
    private javax.swing.JLabel Ln;
    private javax.swing.JLabel Lq;
    private javax.swing.JLabel Num;
    private javax.swing.JLabel Pn;
    private javax.swing.JLabel Po;
    private javax.swing.JLabel Ro;
    private javax.swing.JLabel W;
    private javax.swing.JLabel Wn;
    private javax.swing.JLabel Wq;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JTextField cs;
    private javax.swing.JTextField cte;
    private javax.swing.JTextField cts;
    private javax.swing.JTextField ctse;
    private javax.swing.JTextField h;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lambda;
    private javax.swing.JTextField mu;
    private javax.swing.JTextField n;
    private javax.swing.JTextField n1;
    // End of variables declaration//GEN-END:variables
}
